# nix/quality-report/default.nix
#
# Aggregated static-analysis report. Runs every tool the flake exposes with
# `set +e` (never short-circuits), captures each tool's stdout/stderr, wall-time,
# and exit code, and emits a single markdown report plus the raw logs.
#
# Exposed as:
#   nix build .#quality-report        → result/quality-report.md + result/raw/*
#   nix run   .#quality-report        → prints the markdown to stdout
#   nix run   .#update-quality-report → copies the markdown to nix/quality-report.md
#
# Static analysis only. It deliberately does NOT run `go test` — the nats-server
# suite is large, sharded, and needs ports/time the sandbox does not give. Run
# tests separately (see scripts/ and the dev shell).
#
{
  pkgs,
  src,
  vendoredSource,
}:

let
  versions = import ../versions.nix { inherit pkgs; };
in
pkgs.runCommand "nats-server-quality-report"
  {
    nativeBuildInputs = [
      versions.go
      versions.golangci-lint
      versions.gosec
      versions.nixfmt
      versions.deadnix
      versions.statix
      pkgs.coreutils
      pkgs.findutils
    ];
    inherit vendoredSource src;
  }
  ''
    set +e
    export HOME=$(mktemp -d)
    export CGO_ENABLED=0
    export GOTOOLCHAIN=local
    export GOFLAGS=-mod=vendor
    export GOLANGCI_LINT_CACHE=$(mktemp -d)
    export SOURCE_DATE_EPOCH=1

    mkdir -p $out/raw
    REPORT=$out/quality-report.md

    # Vendored tree for the Go tools; pristine src for the Nix tools.
    cp -r $vendoredSource ./gosrc && chmod -R +w ./gosrc

    # runtool <name> <cmd...> — run a tool, capture output + exit + duration.
    # NOT wrapped in a subshell: the EXITS/SECS updates must land in this shell,
    # so callers cd in and out around it rather than using ( ... ).
    declare -A EXITS
    declare -A SECS
    runtool() {
      local name="$1"; shift
      local start end
      start=$(date +%s)
      "$@" > "$out/raw/$name.log" 2>&1
      EXITS[$name]=$?
      end=$(date +%s)
      SECS[$name]=$((end - start))
    }

    cd ./gosrc
    runtool go-vet   go vet ./...
    runtool golangci-lint               golangci-lint run --config .golangci.yml --modules-download-mode=vendor ./...
    runtool golangci-lint-comprehensive golangci-lint run --config .golangci-comprehensive.yml --modules-download-mode=vendor ./...
    runtool gosec    gosec -exclude=G104,G115,G404 -exclude-dir=vendor ./...
    cd ..

    cp -r $src ./nixsrc && chmod -R +w ./nixsrc
    cd ./nixsrc
    runtool nixfmt   sh -c "find . -name '*.nix' -not -path './vendor/*' -print0 | xargs -0 nixfmt --check"
    runtool deadnix  deadnix --fail flake.nix nix
    runtool statix   statix check -o errfmt
    cd ..

    # Render the summary.
    {
      echo "# nats-server — static analysis report"
      echo
      echo "Generated by \`nix run .#quality-report\` (SOURCE_DATE_EPOCH pinned)."
      echo
      echo "| Tool | Result | Exit | Seconds |"
      echo "| --- | --- | ---: | ---: |"
      for name in go-vet golangci-lint golangci-lint-comprehensive gosec nixfmt deadnix statix; do
        code=''${EXITS[$name]}
        secs=''${SECS[$name]}
        if [ "$code" -eq 0 ]; then result="clean"; else result="findings"; fi
        echo "| $name | $result | $code | $secs |"
      done
      echo
      echo "Raw output for each tool is under \`raw/<tool>.log\`."
      echo
      for name in go-vet golangci-lint golangci-lint-comprehensive gosec nixfmt deadnix statix; do
        echo "## $name (exit ''${EXITS[$name]})"
        echo
        echo '```'
        # Cap each section so the report stays readable; full logs are in raw/.
        head -n 200 "$out/raw/$name.log"
        echo '```'
        echo
      done
    } > "$REPORT"

    # Always succeed — the report captures failures; it does not become one.
    exit 0
  ''
